server:
  port: ${SERVER_PORT:8081}

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/trendtube}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Priya@123}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    
api:
  key: ${API_KEY:your-api-key-here}

springdoc:
  swagger-ui:
    path: /swagger-ui.html